---

- name: Generate config files
  hosts: all
  gather_facts: false

  tasks:
    
  - name: Generate config
    template:
      src: /etc/ansible/templates/template_mpls_bgp.j2
      dest: /etc/ansible/config/{{ inventory_hostname }}.cfg

#  - name: Add config to devices
#   junipernetworks.junos.junos_config:
#     src: /etc/ansible/config/{{ inventory_hostname }}.cfg
#     update: update
#